language: node_js
node_js:
- 4
- 5
- 6
- node 

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-installer
sudo: required
dist: trusty
  
env:
- CXX="g++-4.8" KIBANA_VERSION="5.0.0-beta1"

services:
  - elasticsearch

before_script:
- npm install -g gulp
- wget -O kibana.tar.gz https://github.com/elastic/kibana/archive/v${KIBANA_VERSION}.tar.gz
- wget -O elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${KIBANA_VERSION}.tar.gz
- mkdir -p kibana && tar -zxf kibana.tar.gz -C kibana --strip-components=1
- mkdir -p elasticsearch && tar -zxf elasticsearch.tar.gz -C elasticsearch --strip-components=1
- sudo apt-get install oracle-java8-set-default
- sh -c 'cd kibana && npm install'
- ./elasticsearch/bin/elasticsearch 
- ./kibana/bin/kibana --no-ssl 
- sleep 20
- curl -O https://raw.githubusercontent.com/rockymadden/transfer-cli/master/src/transfer && chmod +x transfer

script:
- gulp build
- gulp package
- ./kibana/bin/kibana-plugin install $(./transfer upload target/mathlion-${KIBANA_VERSION}.zip)



deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: pJitDpcL+ApeS39FK96Jm4o+5grv/XmfnPO0EK753WvF+biMjvDLE2/7vKF0jUzHNZrNVGmLSXLxv0JqIliDyhS7H1SLiOrlQb/JpROJy44W8InDVW00YcpUXqezMrX4J2w5LdhlMZ6X5C8uo6VEI4DmexT6apQ1atWXa3Ew/ZaAzVNvnXq3S1NasAJxBZsZ+vOaJM/eubgpQ61z2iww/S9Q4U32RSG6/fX1xZ/rj2Mc0VWzdT3jBr4v8ROooG42n33T8zqTfuw/Ml5yqjy+a7niCZ+mJESWWnZHC773xlyo2aEOBnsMrdxrCgO+xqZo5BC3wWssMmXFaMIkgC380IOapM0/r7rG+tLhBilGsx0nxeE8AR2PoZXGPAxEb2obqr8s1e8Cex6JGGY8WWp9aytRUgxXsWRyV6dtEef9mRVhMxXC83cfBE4WyVbL054E2ePlhTFD6UwzHR+86YK/jT+05UoQlGDmEFPB4uCxZBhHTta+hJ+fvcxTfqDltL+PqZ65Z3DQP38PTiDjVeuthIJ15TtqO5AFOH5FR1vlEG4zsMfc/Vc4voHzz/BqxK7RFM27xM8OfYqwMAzNh58KriJS5ALwgP7ejM2M4RkmrwOcC8wcCI16vJk5TC66vVU79eWpAgL/oNJppOiHC3q/sSuJWmCUteDdGEJeMCP5AMg=
  file: target/mathlion-*.zip
  skip_cleanup: true
  on:
    repo: fermiumlabs/mathlion
    tags: true
    node: 4      
notifications:
  email: false
