site_name: Mathlion

pages:
- Home: index.md
- Mathematical costants: costants.md
- Mathematical operators: operators.md
- Measurement units: units.md
- Functions: functions/index.md
  - abs.md
  - acos.md
  - acosh.md
  - acot.md
  - acoth.md
  - acsc.md
  - acsch.md
  - add.md
  - and.md
  - arg.md
  - asec.md
  - asech.md
  - asin.md
  - asinh.md
  - atan.md
  - atan2.md
  - atanh.md
  - bellNumbers.md
  - bignumber.md
  - bitAnd.md
  - bitNot.md
  - bitOr.md
  - bitXor.md
  - boolean.md
  - catalan.md
  - cbrt.md
  - ceil.md
  - chain.md
  - clone.md
  - combinations.md
  - compare.md
  - compile.md
  - complex.md
  - composition.md
  - concat.md
  - config.md
  - conj.md
  - cos.md
  - cosh.md
  - cot.md
  - coth.md
  - createUnit.md
  - cross.md
  - csc.md
  - csch.md
  - cube.md
  - deepEqual.md
  - det.md
  - diag.md
  - distance.md
  - divide.md
  - dot.md
  - dotDivide.md
  - dotMultiply.md
  - dotPow.md
  - equal.md
  - eval.md
  - exp.md
  - eye.md
  - factorial.md
  - filter.md
  - fix.md
  - flatten.md
  - floor.md
  - forEach.md
  - format.md
  - fraction.md
  - gamma.md
  - gcd.md
  - help.md
  - hypot.md
  - im.md
  - import.md
  - index.md
  - intersect.md
  - inv.md
  - isInteger.md
  - isNaN.md
  - isNegative.md
  - isNumeric.md
  - isPositive.md
  - isPrime.md
  - isZero.md
  - kldivergence.md
  - larger.md
  - largerEq.md
  - lcm.md
  - leftShift.md
  - list.txt
  - log.md
  - log10.md
  - lsolve.md
  - lup.md
  - lusolve.md
  - map.md
  - matrix.md
  - max.md
  - mean.md
  - median.md
  - min.md
  - mod.md
  - mode.md
  - multinomial.md
  - multiply.md
  - norm.md
  - not.md
  - nthRoot.md
  - number.md
  - ones.md
  - or.md
  - parse.md
  - parser.md
  - partitionSelect.md
  - permutations.md
  - pickRandom.md
  - pow.md
  - print.md
  - prod.md
  - quantileSeq.md
  - random.md
  - randomInt.md
  - range.md
  - re.md
  - resize.md
  - rightArithShift.md
  - rightLogShift.md
  - round.md
  - sec.md
  - sech.md
  - sign.md
  - sin.md
  - sinh.md
  - size.md
  - slu.md
  - smaller.md
  - smallerEq.md
  - sort.md
  - sparse.md
  - splitUnit.md
  - sqrt.md
  - square.md
  - squeeze.md
  - std.md
  - stirlingS2.md
  - string.md
  - subset.md
  - subtract.md
  - sum.md
  - tan.md
  - tanh.md
  - to.md
  - trace.md
  - transpose.md
  - typed.md
  - typeof.md
  - unaryMinus.md
  - unaryPlus.md
  - unequal.md
  - unit.md
  - usolve.md
  - var.md
  - xgcd.md
  - xor.md
  - zeros.md  
