site_name: Mathlion

pages:
- Home: index.md
- Mathematical costants: costants.md
- Mathematical operators: operators.md
- Measurement units: units.md
- Functions: functions/index.md
  - functions/functions/abs.md
  - functions/functions/acos.md
  - functions/functions/acosh.md
  - functions/functions/acot.md
  - functions/functions/acoth.md
  - functions/functions/acsc.md
  - functions/functions/acsch.md
  - functions/functions/add.md
  - functions/functions/and.md
  - functions/functions/arg.md
  - functions/functions/asec.md
  - functions/functions/asech.md
  - functions/functions/asin.md
  - functions/functions/asinh.md
  - functions/functions/atan.md
  - functions/functions/atan2.md
  - functions/functions/atanh.md
  - functions/functions/bellNumbers.md
  - functions/functions/bignumber.md
  - functions/functions/bitAnd.md
  - functions/functions/bitNot.md
  - functions/functions/bitOr.md
  - functions/functions/bitXor.md
  - functions/functions/boolean.md
  - functions/functions/catalan.md
  - functions/functions/cbrt.md
  - functions/functions/ceil.md
  - functions/functions/chain.md
  - functions/functions/clone.md
  - functions/functions/combinations.md
  - functions/functions/compare.md
  - functions/functions/compile.md
  - functions/functions/complex.md
  - functions/functions/composition.md
  - functions/functions/concat.md
  - functions/functions/config.md
  - functions/functions/conj.md
  - functions/functions/cos.md
  - functions/functions/cosh.md
  - functions/functions/cot.md
  - functions/functions/coth.md
  - functions/functions/createUnit.md
  - functions/functions/cross.md
  - functions/functions/csc.md
  - functions/functions/csch.md
  - functions/functions/cube.md
  - functions/functions/deepEqual.md
  - functions/functions/det.md
  - functions/functions/diag.md
  - functions/functions/distance.md
  - functions/functions/divide.md
  - functions/functions/dot.md
  - functions/functions/dotDivide.md
  - functions/functions/dotMultiply.md
  - functions/functions/dotPow.md
  - functions/functions/equal.md
  - functions/functions/eval.md
  - functions/functions/exp.md
  - functions/functions/eye.md
  - functions/functions/factorial.md
  - functions/functions/filter.md
  - functions/functions/fix.md
  - functions/functions/flatten.md
  - functions/functions/floor.md
  - functions/functions/forEach.md
  - functions/functions/format.md
  - functions/functions/fraction.md
  - functions/functions/gamma.md
  - functions/functions/gcd.md
  - functions/functions/help.md
  - functions/functions/hypot.md
  - functions/functions/im.md
  - functions/functions/import.md
  - functions/functions/index.md
  - functions/functions/intersect.md
  - functions/functions/inv.md
  - functions/functions/isInteger.md
  - functions/functions/isNaN.md
  - functions/functions/isNegative.md
  - functions/functions/isNumeric.md
  - functions/functions/isPositive.md
  - functions/functions/isPrime.md
  - functions/functions/isZero.md
  - functions/functions/kldivergence.md
  - functions/functions/larger.md
  - functions/functions/largerEq.md
  - functions/functions/lcm.md
  - functions/functions/leftShift.md
  - functions/functions/list.txt
  - functions/functions/log.md
  - functions/functions/log10.md
  - functions/functions/lsolve.md
  - functions/functions/lup.md
  - functions/functions/lusolve.md
  - functions/functions/map.md
  - functions/functions/matrix.md
  - functions/functions/max.md
  - functions/functions/mean.md
  - functions/functions/median.md
  - functions/functions/min.md
  - functions/functions/mod.md
  - functions/functions/mode.md
  - functions/functions/multinomial.md
  - functions/functions/multiply.md
  - functions/functions/norm.md
  - functions/functions/not.md
  - functions/functions/nthRoot.md
  - functions/functions/number.md
  - functions/functions/ones.md
  - functions/functions/or.md
  - functions/functions/parse.md
  - functions/functions/parser.md
  - functions/functions/partitionSelect.md
  - functions/functions/permutations.md
  - functions/functions/pickRandom.md
  - functions/functions/pow.md
  - functions/functions/print.md
  - functions/functions/prod.md
  - functions/functions/quantileSeq.md
  - functions/functions/random.md
  - functions/functions/randomInt.md
  - functions/functions/range.md
  - functions/functions/re.md
  - functions/functions/resize.md
  - functions/functions/rightArithShift.md
  - functions/functions/rightLogShift.md
  - functions/functions/round.md
  - functions/functions/sec.md
  - functions/functions/sech.md
  - functions/functions/sign.md
  - functions/functions/sin.md
  - functions/functions/sinh.md
  - functions/functions/size.md
  - functions/functions/slu.md
  - functions/functions/smaller.md
  - functions/functions/smallerEq.md
  - functions/functions/sort.md
  - functions/functions/sparse.md
  - functions/functions/splitUnit.md
  - functions/functions/sqrt.md
  - functions/functions/square.md
  - functions/functions/squeeze.md
  - functions/functions/std.md
  - functions/functions/stirlingS2.md
  - functions/functions/string.md
  - functions/functions/subset.md
  - functions/functions/subtract.md
  - functions/functions/sum.md
  - functions/functions/tan.md
  - functions/functions/tanh.md
  - functions/functions/to.md
  - functions/functions/trace.md
  - functions/functions/transpose.md
  - functions/functions/typed.md
  - functions/functions/typeof.md
  - functions/functions/unaryMinus.md
  - functions/functions/unaryPlus.md
  - functions/functions/unequal.md
  - functions/functions/unit.md
  - functions/functions/usolve.md
  - functions/functions/var.md
  - functions/functions/xgcd.md
  - functions/functions/xor.md
  - functions/functions/zeros.md  
