site_name: Mathlion
theme: readthedocs
pages:
- Home: index.md
- Mathematical costants: costants.md
- Mathematical operators: operators.md
- Measurement units: units.md
- Functions: functions.md
- Functions list:
  - functions/abs.md
  - functions/acos.md
  - functions/acosh.md
  - functions/acot.md
  - functions/acoth.md
  - functions/acsc.md
  - functions/acsch.md
  - functions/add.md
  - functions/and.md
  - functions/arg.md
  - functions/asec.md
  - functions/asech.md
  - functions/asin.md
  - functions/asinh.md
  - functions/atan.md
  - functions/atan2.md
  - functions/atanh.md
  - functions/bellNumbers.md
  - functions/bignumber.md
  - functions/bitAnd.md
  - functions/bitNot.md
  - functions/bitOr.md
  - functions/bitXor.md
  - functions/boolean.md
  - functions/catalan.md
  - functions/cbrt.md
  - functions/ceil.md
  - functions/chain.md
  - functions/clone.md
  - functions/combinations.md
  - functions/compare.md
  - functions/compile.md
  - functions/complex.md
  - functions/composition.md
  - functions/concat.md
  - functions/config.md
  - functions/conj.md
  - functions/cos.md
  - functions/cosh.md
  - functions/cot.md
  - functions/coth.md
  - functions/createUnit.md
  - functions/cross.md
  - functions/csc.md
  - functions/csch.md
  - functions/cube.md
  - functions/deepEqual.md
  - functions/det.md
  - functions/diag.md
  - functions/distance.md
  - functions/divide.md
  - functions/dot.md
  - functions/dotDivide.md
  - functions/dotMultiply.md
  - functions/dotPow.md
  - functions/equal.md
  - functions/eval.md
  - functions/exp.md
  - functions/eye.md
  - functions/factorial.md
  - functions/filter.md
  - functions/fix.md
  - functions/flatten.md
  - functions/floor.md
  - functions/forEach.md
  - functions/format.md
  - functions/fraction.md
  - functions/gamma.md
  - functions/gcd.md
  - functions/help.md
  - functions/hypot.md
  - functions/im.md
  - functions/import.md
  - functions/intersect.md
  - functions/inv.md
  - functions/isInteger.md
  - functions/isNaN.md
  - functions/isNegative.md
  - functions/isNumeric.md
  - functions/isPositive.md
  - functions/isPrime.md
  - functions/isZero.md
  - functions/kldivergence.md
  - functions/larger.md
  - functions/largerEq.md
  - functions/lcm.md
  - functions/leftShift.md
  - functions/log.md
  - functions/log10.md
  - functions/lsolve.md
  - functions/lup.md
  - functions/lusolve.md
  - functions/map.md
  - functions/matrix.md
  - functions/max.md
  - functions/mean.md
  - functions/median.md
  - functions/min.md
  - functions/mod.md
  - functions/mode.md
  - functions/multinomial.md
  - functions/multiply.md
  - functions/norm.md
  - functions/not.md
  - functions/nthRoot.md
  - functions/number.md
  - functions/ones.md
  - functions/or.md
  - functions/parse.md
  - functions/parser.md
  - functions/partitionSelect.md
  - functions/permutations.md
  - functions/pickRandom.md
  - functions/pow.md
  - functions/print.md
  - functions/prod.md
  - functions/quantileSeq.md
  - functions/random.md
  - functions/randomInt.md
  - functions/range.md
  - functions/re.md
  - functions/resize.md
  - functions/rightArithShift.md
  - functions/rightLogShift.md
  - functions/round.md
  - functions/sec.md
  - functions/sech.md
  - functions/sign.md
  - functions/sin.md
  - functions/sinh.md
  - functions/size.md
  - functions/slu.md
  - functions/smaller.md
  - functions/smallerEq.md
  - functions/sort.md
  - functions/sparse.md
  - functions/splitUnit.md
  - functions/sqrt.md
  - functions/square.md
  - functions/squeeze.md
  - functions/std.md
  - functions/stirlingS2.md
  - functions/string.md
  - functions/subset.md
  - functions/subtract.md
  - functions/sum.md
  - functions/tan.md
  - functions/tanh.md
  - functions/to.md
  - functions/trace.md
  - functions/transpose.md
  - functions/typed.md
  - functions/typeof.md
  - functions/unaryMinus.md
  - functions/unaryPlus.md
  - functions/unequal.md
  - functions/unit.md
  - functions/usolve.md
  - functions/var.md
  - functions/xgcd.md
  - functions/xor.md
  - functions/zeros.md  
